private-events
unhandledError: anException

	self close